<?php
/**
 * CategoryOptionsDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * CategoryOptionsDtoTest Class Doc Comment
 *
 * @category    Class
 * @description A list of the different options which can be used with this category.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CategoryOptionsDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CategoryOptionsDto"
     */
    public function testCategoryOptionsDto()
    {
    }

    /**
     * Test attribute "advertisement"
     */
    public function testPropertyAdvertisement()
    {
    }

    /**
     * Test attribute "advertisement_price_optional"
     */
    public function testPropertyAdvertisementPriceOptional()
    {
    }

    /**
     * Test attribute "variants_by_color_pattern_allowed"
     */
    public function testPropertyVariantsByColorPatternAllowed()
    {
    }

    /**
     * Test attribute "offers_with_product_publication_enabled"
     */
    public function testPropertyOffersWithProductPublicationEnabled()
    {
    }

    /**
     * Test attribute "product_creation_enabled"
     */
    public function testPropertyProductCreationEnabled()
    {
    }

    /**
     * Test attribute "product_ean_required"
     */
    public function testPropertyProductEanRequired()
    {
    }
}
