<?php
/**
 * CompatibilityListSupportedCategoriesDtoSupportedCategoriesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * CompatibilityListSupportedCategoriesDtoSupportedCategoriesTest Class Doc Comment
 *
 * @category    Class
 * @description CompatibilityListSupportedCategoriesDtoSupportedCategories
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CompatibilityListSupportedCategoriesDtoSupportedCategoriesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CompatibilityListSupportedCategoriesDtoSupportedCategories"
     */
    public function testCompatibilityListSupportedCategoriesDtoSupportedCategories()
    {
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "items_type"
     */
    public function testPropertyItemsType()
    {
    }

    /**
     * Test attribute "input_type"
     */
    public function testPropertyInputType()
    {
    }

    /**
     * Test attribute "validation_rules"
     */
    public function testPropertyValidationRules()
    {
    }
}
