<?php
/**
 * MyBidResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * MyBidResponseTest Class Doc Comment
 *
 * @category    Class
 * @description bid response
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MyBidResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MyBidResponse"
     */
    public function testMyBidResponse()
    {
    }

    /**
     * Test attribute "max_amount"
     */
    public function testPropertyMaxAmount()
    {
    }

    /**
     * Test attribute "minimal_price_met"
     */
    public function testPropertyMinimalPriceMet()
    {
    }

    /**
     * Test attribute "high_bidder"
     */
    public function testPropertyHighBidder()
    {
    }

    /**
     * Test attribute "auction"
     */
    public function testPropertyAuction()
    {
    }
}
