<?php
/**
 * OfferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * OfferTest Class Doc Comment
 *
 * @category    Class
 * @description Single offer data
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OfferTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Offer"
     */
    public function testOffer()
    {
    }

    /**
     * Test attribute "additional_services"
     */
    public function testPropertyAdditionalServices()
    {
    }

    /**
     * Test attribute "after_sales_services"
     */
    public function testPropertyAfterSalesServices()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "compatibility_list"
     */
    public function testPropertyCompatibilityList()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "delivery"
     */
    public function testPropertyDelivery()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "external"
     */
    public function testPropertyExternal()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "parameters"
     */
    public function testPropertyParameters()
    {
    }

    /**
     * Test attribute "payments"
     */
    public function testPropertyPayments()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "promotion"
     */
    public function testPropertyPromotion()
    {
    }

    /**
     * Test attribute "publication"
     */
    public function testPropertyPublication()
    {
    }

    /**
     * Test attribute "selling_mode"
     */
    public function testPropertySellingMode()
    {
    }

    /**
     * Test attribute "size_table"
     */
    public function testPropertySizeTable()
    {
    }

    /**
     * Test attribute "stock"
     */
    public function testPropertyStock()
    {
    }

    /**
     * Test attribute "tecdoc_specification"
     */
    public function testPropertyTecdocSpecification()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "validation"
     */
    public function testPropertyValidation()
    {
    }
}
