<?php
/**
 * StringCategoryProductParameterAllOfRestrictionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * StringCategoryProductParameterAllOfRestrictionsTest Class Doc Comment
 *
 * @category    Class
 * @description The restrictions on values of this parameter.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StringCategoryProductParameterAllOfRestrictionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StringCategoryProductParameterAllOfRestrictions"
     */
    public function testStringCategoryProductParameterAllOfRestrictions()
    {
    }

    /**
     * Test attribute "min_length"
     */
    public function testPropertyMinLength()
    {
    }

    /**
     * Test attribute "max_length"
     */
    public function testPropertyMaxLength()
    {
    }

    /**
     * Test attribute "allowed_number_of_values"
     */
    public function testPropertyAllowedNumberOfValues()
    {
    }
}
