<?php
/**
 * BatchOfferModificationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BatchOfferModificationApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BatchOfferModificationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getGeneralReportUsingGET
     *
     * Modification command summary.
     *
     */
    public function testGetGeneralReportUsingGET()
    {
    }

    /**
     * Test case for getPriceModificationCommandStatusUsingGET
     *
     * Change price command summary.
     *
     */
    public function testGetPriceModificationCommandStatusUsingGET()
    {
    }

    /**
     * Test case for getPriceModificationCommandTasksStatusesUsingGET
     *
     * Change price command detailed report.
     *
     */
    public function testGetPriceModificationCommandTasksStatusesUsingGET()
    {
    }

    /**
     * Test case for getQuantityModificationCommandStatusUsingGET
     *
     * Change quantity command summary.
     *
     */
    public function testGetQuantityModificationCommandStatusUsingGET()
    {
    }

    /**
     * Test case for getQuantityModificationCommandTasksStatusesUsingGET
     *
     * Change quantity command detailed report.
     *
     */
    public function testGetQuantityModificationCommandTasksStatusesUsingGET()
    {
    }

    /**
     * Test case for getTasksUsingGET
     *
     * Modification command detailed report.
     *
     */
    public function testGetTasksUsingGET()
    {
    }

    /**
     * Test case for modificationCommandUsingPUT
     *
     * Batch offer modification.
     *
     */
    public function testModificationCommandUsingPUT()
    {
    }

    /**
     * Test case for priceModificationCommandUsingPUT
     *
     * Batch offer price modification.
     *
     */
    public function testPriceModificationCommandUsingPUT()
    {
    }

    /**
     * Test case for quantityModificationCommandUsingPUT
     *
     * Batch offer quantity modification.
     *
     */
    public function testQuantityModificationCommandUsingPUT()
    {
    }
}
