<?php
/**
 * ClassifiedsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ClassifiedsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClassifiedsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for assignClassifiedPackagesUsingPUT
     *
     * Assign packages to a classified.
     *
     */
    public function testAssignClassifiedPackagesUsingPUT()
    {
    }

    /**
     * Test case for getClassifiedPackageConfigurationUsingGET
     *
     * Get the configuration of a package.
     *
     */
    public function testGetClassifiedPackageConfigurationUsingGET()
    {
    }

    /**
     * Test case for getClassifiedPackageConfigurationsForCategoryUsingGET
     *
     * Get configurations of packages.
     *
     */
    public function testGetClassifiedPackageConfigurationsForCategoryUsingGET()
    {
    }

    /**
     * Test case for getClassifiedPackagesUsingGET
     *
     * Get classified packages assigned to an offer.
     *
     */
    public function testGetClassifiedPackagesUsingGET()
    {
    }
}
