<?php
/**
 * DeliveryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DeliveryApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeliveryApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createShippingRatesSetUsingPOST
     *
     * Create a new shipping rates set.
     *
     */
    public function testCreateShippingRatesSetUsingPOST()
    {
    }

    /**
     * Test case for getListOfDeliveryMethodsUsingGET
     *
     * Get the list of delivery methods.
     *
     */
    public function testGetListOfDeliveryMethodsUsingGET()
    {
    }

    /**
     * Test case for getListOfShippingRatestUsingGET
     *
     * Get the user's shipping rates.
     *
     */
    public function testGetListOfShippingRatestUsingGET()
    {
    }

    /**
     * Test case for getOfferShippingRatesGET
     *
     * [BETA] Get shipping rates assigned to an offer.
     *
     */
    public function testGetOfferShippingRatesGET()
    {
    }

    /**
     * Test case for getSaleDeliverySettings
     *
     * Get the user's delivery settings.
     *
     */
    public function testGetSaleDeliverySettings()
    {
    }

    /**
     * Test case for getShippingRatesSetUsingGET
     *
     * Get the details of a shipping rates set.
     *
     */
    public function testGetShippingRatesSetUsingGET()
    {
    }

    /**
     * Test case for modifyShippingRatesSetUsingPUT
     *
     * Edit a user's shipping rates set.
     *
     */
    public function testModifyShippingRatesSetUsingPUT()
    {
    }

    /**
     * Test case for putSaleDeliverySettings
     *
     * Modify the user's delivery settings.
     *
     */
    public function testPutSaleDeliverySettings()
    {
    }
}
