<?php
/**
 * DisputesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DisputesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DisputesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addMessageToDisputeUsingPOST
     *
     * Add a message to a dispute.
     *
     */
    public function testAddMessageToDisputeUsingPOST()
    {
    }

    /**
     * Test case for createAnAttachmentUsingPOST
     *
     * Create an attachment declaration.
     *
     */
    public function testCreateAnAttachmentUsingPOST()
    {
    }

    /**
     * Test case for getAttachmentUsingGET
     *
     * Get an attachment.
     *
     */
    public function testGetAttachmentUsingGET()
    {
    }

    /**
     * Test case for getDisputeUsingGET
     *
     * Get a single dispute.
     *
     */
    public function testGetDisputeUsingGET()
    {
    }

    /**
     * Test case for getListOfDisputesUsingGET
     *
     * Get the user's disputes.
     *
     */
    public function testGetListOfDisputesUsingGET()
    {
    }

    /**
     * Test case for getMessagesFromDisputeUsingGET
     *
     * Get the messages within a dispute.
     *
     */
    public function testGetMessagesFromDisputeUsingGET()
    {
    }

    /**
     * Test case for uploadDisputeAttachmentUsingPUT
     *
     * Upload a dispute message attachment.
     *
     */
    public function testUploadDisputeAttachmentUsingPUT()
    {
    }
}
