<?php
/**
 * OfferManagementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OfferManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OfferManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changePublicationStatusUsingPUT
     *
     * Batch offer publish / unpublish.
     *
     */
    public function testChangePublicationStatusUsingPUT()
    {
    }

    /**
     * Test case for createChangePriceCommandUsingPUT
     *
     * Modify the Buy Now price in an offer.
     *
     */
    public function testCreateChangePriceCommandUsingPUT()
    {
    }

    /**
     * Test case for createOfferUsingPOST
     *
     * Create a draft offer.
     *
     */
    public function testCreateOfferUsingPOST()
    {
    }

    /**
     * Test case for deleteOfferUsingDELETE
     *
     * Delete a draft offer.
     *
     */
    public function testDeleteOfferUsingDELETE()
    {
    }

    /**
     * Test case for getPublicationReportUsingGET
     *
     * Publish command summary.
     *
     */
    public function testGetPublicationReportUsingGET()
    {
    }

    /**
     * Test case for getPublicationTasksUsingGET
     *
     * Publish command detailed report.
     *
     */
    public function testGetPublicationTasksUsingGET()
    {
    }

    /**
     * Test case for updateOfferUsingPUT
     *
     * Complete a draft offer or edit an offer.
     *
     */
    public function testUpdateOfferUsingPUT()
    {
    }
}
