<?php
/**
 * OrderManagementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrderManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrderShipmentsUsingPOST
     *
     * [BETA] Add a parcel tracking number.
     *
     */
    public function testCreateOrderShipmentsUsingPOST()
    {
    }

    /**
     * Test case for findMapping
     *
     * Get mapping for line item id.
     *
     */
    public function testFindMapping()
    {
    }

    /**
     * Test case for getListOfOrdersUsingGET
     *
     * Get the user's orders.
     *
     */
    public function testGetListOfOrdersUsingGET()
    {
    }

    /**
     * Test case for getOrderEventsStatisticsUsingGET
     *
     * Get order events statistics.
     *
     */
    public function testGetOrderEventsStatisticsUsingGET()
    {
    }

    /**
     * Test case for getOrderEventsUsingGET
     *
     * Get order events.
     *
     */
    public function testGetOrderEventsUsingGET()
    {
    }

    /**
     * Test case for getOrderShipmentsUsingGET
     *
     * [BETA] Get a list of parcel tracking numbers.
     *
     */
    public function testGetOrderShipmentsUsingGET()
    {
    }

    /**
     * Test case for getOrdersDetailsUsingGET
     *
     * Get an order's details.
     *
     */
    public function testGetOrdersDetailsUsingGET()
    {
    }
}
