<?php
/**
 * PaymentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getPaymentIdMapping
     *
     * Mapping of payment identifiers.
     *
     */
    public function testGetPaymentIdMapping()
    {
    }

    /**
     * Test case for getPaymentsOperationHistory
     *
     * Payment operations history.
     *
     */
    public function testGetPaymentsOperationHistory()
    {
    }

    /**
     * Test case for paymentsRefundsGet
     *
     * Get a list of refunded payments.
     *
     */
    public function testPaymentsRefundsGet()
    {
    }

    /**
     * Test case for paymentsRefundsPost
     *
     * Initiate a refund of a payment.
     *
     */
    public function testPaymentsRefundsPost()
    {
    }
}
