<?php
/**
 * PointsOfServiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PointsOfServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PointsOfServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPOSUsingPOST
     *
     * Create a point of service.
     *
     */
    public function testCreatePOSUsingPOST()
    {
    }

    /**
     * Test case for deletePOSUsingDELETE
     *
     * Delete a point of service.
     *
     */
    public function testDeletePOSUsingDELETE()
    {
    }

    /**
     * Test case for getPOSDataUsingGET
     *
     * Get the details of a point of service.
     *
     */
    public function testGetPOSDataUsingGET()
    {
    }

    /**
     * Test case for getPOSListUsingGET
     *
     * Get the user's points of service.
     *
     */
    public function testGetPOSListUsingGET()
    {
    }

    /**
     * Test case for modifyPOSUsingPUT
     *
     * Modify a point of service.
     *
     */
    public function testModifyPOSUsingPUT()
    {
    }
}
