<?php
/**
 * PromotionCampaignsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PromotionCampaignsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PromotionCampaignsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addPromotionToCampaignUsingPOST
     *
     * Create an application for a promotion campaign.
     *
     */
    public function testAddPromotionToCampaignUsingPOST()
    {
    }

    /**
     * Test case for deleteCampaignFromPromotionUsingDELETE
     *
     * Delete a campaign in a promotion.
     *
     */
    public function testDeleteCampaignFromPromotionUsingDELETE()
    {
    }

    /**
     * Test case for deletePromotionCampaignApplicationUsingDELETE
     *
     * Delete an application for promotion campaign.
     *
     */
    public function testDeletePromotionCampaignApplicationUsingDELETE()
    {
    }

    /**
     * Test case for getPromotionCampaignApplicationUsingGET
     *
     * Get an application for promotion campaign.
     *
     */
    public function testGetPromotionCampaignApplicationUsingGET()
    {
    }

    /**
     * Test case for getPromotionCampaignsUsingGET
     *
     * Get the user's promotion campaigns.
     *
     */
    public function testGetPromotionCampaignsUsingGET()
    {
    }
}
