<?php
/**
 * SetsAndRebatesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SetsAndRebatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SetsAndRebatesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPromotionUsingPOST1
     *
     * Create a new promotion.
     *
     */
    public function testCreatePromotionUsingPOST1()
    {
    }

    /**
     * Test case for deactivatePromotionUsingDELETE
     *
     * Deactivate a promotion by id.
     *
     */
    public function testDeactivatePromotionUsingDELETE()
    {
    }

    /**
     * Test case for getPromotionUsingGET
     *
     * Get a promotion data by id.
     *
     */
    public function testGetPromotionUsingGET()
    {
    }

    /**
     * Test case for listSellerPromotionsUsingGET1
     *
     * Get the user's list of promotions.
     *
     */
    public function testListSellerPromotionsUsingGET1()
    {
    }
}
